### ISSUE TITLE
DOCKER_HOST meanings

### ISSUE THREAD

**Issue by yoannfleurydev** [LordGaav/dind-options#4]
Hi,

I'm kind of new in Docker, and I'm wondering, what the point of the `DOCKER_HOST` variable in the example in the `README`? I can't find out the interest of this environment variable. Can you please provide me some information about it?

Thanks.

**Comment by LordGaav** [comment]
Normally, the Docker tools connect to the Docker daemon on localhost. By specifying `DOCKER_HOST` as environment variable, you can make it connect to a Docker daemon on another host.

In the specific use for this Docker image, Gitlab CI will spin up a docker container running the Docker daemon. Setting the environment variable causes the Gitlab CI job to use this Docker daemon.

**Comment by yoannfleurydev** [comment]
Oh, okay. I better understand now why there is 2 underscores in the hostname, it's due to Gitlab hostname translation system. Well, thanks a lot for these explanations! :+1:
